
[functions]
  external_node_modules = ["express","@prisma/client","cors","cross-env","dotenv","firebase-admin","mongodb","serverless-http"]
  node_bundler = "esbuild"

[context.production]
  command = "EXPO_PUBLIC_API_URL=$DEPLOY_URL && npm run build"

[dev]
  functions="api/src"

[build]
  functions="api/src"
  command = "EXPO_PUBLIC_API_URL=$DEPLOY_URL && npm run build"