import { MD3LightTheme as DefaultTheme, MD3Theme } from "react-native-paper";

export const theme: MD3Theme = {
  ...DefaultTheme,
  ...{
    colors: {
      ...DefaultTheme.colors,
      primary: "#FFDF9A",
      onPrimary: "#6B5E41",
      primaryContainer: "#ffdad4",
      onPrimaryContainer: "#400200",
      secondary: "#644fab",
      onSecondary: "#ffffff",
      secondaryContainer: "#e7deff",
      onSecondaryContainer: "#463D66",
      tertiary: "#DF442E",
      onTertiary: "#ffffffff",
      tertiaryContainer: "#FFFCF5",
      onTertiaryContainer: "#3d3524ff",
      error: "#ba1a1a",
      onError: "#ffffff",
      errorContainer: "#ffdad6",
      onErrorContainer: "#410002",
      background: "#FFFCF5",
      onBackground: "#1e1b16",
      surface: "#FFF5E0",
      onSurface: "#1e1b16",
      surfaceVariant: "#FFF5E0",
      onSurfaceVariant: "#4d4639",
      outline: "#7e7667",
      outlineVariant: "#d0c5b4",
      shadow: "#000000",
      scrim: "#000000",
      inverseSurface: "#33302a",
      inverseOnSurface: "#f7f0e7",
      inversePrimary: "#f0c048",
      elevation: {
        level0: "transparent",
        level1: "#f8f3f2",
        level2: "#f4eeeb",
        level3: "#f0e9e3",
        level4: "#efe8e0",
        level5: "#ece5db",
      },
      surfaceDisabled: "rgba(30, 27, 22, 0.12)",
      onSurfaceDisabled: "rgba(30, 27, 22, 0.38)",
      backdrop: "rgba(54, 48, 36, 0.4)",
    },
  },
};
