-- The app treats contacts as one row per (author, type) — that's the whole
-- premise of ContactEditScreen's upsert — but nothing enforced it at the DB
-- level, so the client had to upsert on the surrogate "id" instead. For a
-- brand-new contact that's never known, so onConflict:"id" could never
-- actually dedupe by type; worse, contacts.id is GENERATED BY DEFAULT AS
-- IDENTITY (explicit ids are allowed), so if the sequence ever falls behind
-- max(id) (e.g. after an import/restore with explicit ids), a freshly
-- generated id can collide with an existing row owned by a different user.
-- RLS then hides that row from the ON CONFLICT (id) DO UPDATE branch, and
-- Postgres reports a plain duplicate-key 409 instead of upserting — this is
-- what broke contact creation while creating a biznisz.
--
-- Fix (paired with a ContactEditScreen.tsx change to upsert on author,type
-- and never send id): make (author, type) the real, enforced unique key.

-- Keep the most recently created row per (author, type); drop older dupes,
-- in case any slipped in before this constraint existed.
DELETE FROM "public"."contacts" a
USING "public"."contacts" b
WHERE a."author" = b."author"
  AND a."type" = b."type"
  AND a."id" < b."id";

ALTER TABLE "public"."contacts"
  ADD CONSTRAINT "contacts_author_type_key" UNIQUE ("author", "type");
