-- Newsletter sending, built on the existing notify edge function.
--
-- Flow:
--   INSERT INTO public.newsletters (subject, title, body)  -- admin, via Studio / SQL editor
--     └─ AFTER INSERT trigger (trigger_notify_on_record_created)
--          └─ pg_net POST → /functions/v1/notify   { table: "newsletters", record: {...} }
--               └─ notify resolves recipients via get_newsletter_recipients()
--                    └─ one email per recipient, greeted by name + unsubscribe link
--
-- Recipients:
--   recipients IS NULL (or empty)  → every profile with newsletter = true
--   recipients = '{a@b.hu,...}'    → exactly those addresses (test sends, targeted mails)
-- Unsubscribed addresses are always skipped, in both modes.

-------------------------------------------------------------------
-- 1. newsletters — one row per newsletter issue
-------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."newsletters" (
    "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"   timestamp with time zone NOT NULL DEFAULT "now"(),
    "subject"      "text" NOT NULL,
    "title"        "text",
    "body"         "text" NOT NULL,
    "cta_label"    "text",
    "cta_url"      "text",
    "recipients"   "text"[],
    "status"       "text" NOT NULL DEFAULT 'pending',
    "sent_count"   integer NOT NULL DEFAULT 0,
    "failed_count" integer NOT NULL DEFAULT 0,
    "error"        "text",
    "sent_at"      timestamp with time zone,
    CONSTRAINT "newsletters_status_check"
      CHECK ("status" IN ('pending', 'sending', 'sent', 'failed'))
);

ALTER TABLE "public"."newsletters" OWNER TO "postgres";

COMMENT ON TABLE  "public"."newsletters"            IS 'One row per newsletter issue. Inserting a row sends it (see notify edge function).';
COMMENT ON COLUMN "public"."newsletters"."subject"  IS 'Email subject line.';
COMMENT ON COLUMN "public"."newsletters"."title"    IS 'Optional headline rendered above the body. Falls back to subject.';
COMMENT ON COLUMN "public"."newsletters"."body"     IS 'HTML fragment for the email body. Inline styles only (Gmail strips <style>).';
COMMENT ON COLUMN "public"."newsletters"."recipients" IS 'NULL/empty = all subscribers (profiles.newsletter = true). Otherwise exactly these email addresses.';
COMMENT ON COLUMN "public"."newsletters"."status"   IS 'pending → sending → sent | failed. Written back by the notify edge function.';

-- RLS on with no policies: nothing readable or writable by anon/authenticated.
-- Only postgres / service_role (which bypass RLS) can create and read newsletters.
ALTER TABLE "public"."newsletters" ENABLE ROW LEVEL SECURITY;

-------------------------------------------------------------------
-- 2. newsletter_unsubscribes — suppression list
--
--    Covers addresses that have no profile (manually added recipients)
--    and doubles as a tombstone for users who unsubscribe from an email.
-------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."newsletter_unsubscribes" (
    "email"      "text" PRIMARY KEY,
    "created_at" timestamp with time zone NOT NULL DEFAULT "now"()
);

ALTER TABLE "public"."newsletter_unsubscribes" OWNER TO "postgres";

COMMENT ON TABLE "public"."newsletter_unsubscribes"
  IS 'Addresses that clicked unsubscribe. Always lowercase. Filtered out of every send.';

ALTER TABLE "public"."newsletter_unsubscribes" ENABLE ROW LEVEL SECURITY;

-------------------------------------------------------------------
-- 3. get_newsletter_recipients(text[]) — resolve the audience
--
--    Returns email + full_name so the edge function can greet people
--    by name. Service role only: it exposes auth.users emails.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."get_newsletter_recipients"("p_emails" "text"[] DEFAULT NULL)
RETURNS TABLE("email" "text", "full_name" "text")
LANGUAGE "sql"
SECURITY DEFINER
SET "search_path" = "public"
AS $$
  WITH targets AS (
    -- Explicit list: exactly the given addresses, subscription state ignored.
    SELECT DISTINCT
      lower(trim(e.address))::text AS email,
      (
        SELECT p.full_name
        FROM public.profiles p
        JOIN auth.users u ON u.id = p.id
        WHERE lower(u.email) = lower(trim(e.address))
        LIMIT 1
      ) AS full_name
    FROM unnest(COALESCE(p_emails, ARRAY[]::text[])) AS e(address)
    WHERE p_emails IS NOT NULL
      AND array_length(p_emails, 1) > 0
      AND trim(e.address) <> ''

    UNION

    -- Default: everybody subscribed to the newsletter.
    SELECT DISTINCT
      lower(u.email)::text AS email,
      p.full_name
    FROM public.profiles p
    JOIN auth.users u ON u.id = p.id
    WHERE (p_emails IS NULL OR array_length(p_emails, 1) IS NULL)
      AND p.newsletter = true
      AND u.email IS NOT NULL
      AND u.email <> ''
  )
  SELECT t.email, t.full_name
  FROM targets t
  WHERE NOT EXISTS (
    SELECT 1 FROM public.newsletter_unsubscribes n WHERE n.email = t.email
  );
$$;

ALTER FUNCTION "public"."get_newsletter_recipients"("text"[]) OWNER TO "postgres";

REVOKE EXECUTE ON FUNCTION "public"."get_newsletter_recipients"("text"[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."get_newsletter_recipients"("text"[]) FROM "anon", "authenticated";

-------------------------------------------------------------------
-- 4. newsletter_unsubscribe(text) — one-click unsubscribe
--
--    Called by the newsletter-unsubscribe edge function *after* it has
--    verified the HMAC token in the link, so it takes a plain email.
--    Service role only — never expose this to anon/authenticated, or
--    anyone could unsubscribe anyone.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."newsletter_unsubscribe"("p_email" "text")
RETURNS boolean
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = "public"
AS $$
DECLARE
  normalized text := lower(trim(p_email));
BEGIN
  IF normalized IS NULL OR normalized = '' THEN
    RETURN false;
  END IF;

  INSERT INTO public.newsletter_unsubscribes (email)
  VALUES (normalized)
  ON CONFLICT (email) DO NOTHING;

  UPDATE public.profiles p
  SET newsletter = false
  FROM auth.users u
  WHERE u.id = p.id
    AND lower(u.email) = normalized
    AND p.newsletter = true;

  RETURN true;
END;
$$;

ALTER FUNCTION "public"."newsletter_unsubscribe"("text") OWNER TO "postgres";

REVOKE EXECUTE ON FUNCTION "public"."newsletter_unsubscribe"("text") FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION "public"."newsletter_unsubscribe"("text") FROM "anon", "authenticated";

-------------------------------------------------------------------
-- 5. Resubscribing from the app clears the tombstone
--
--    Without this, a user who unsubscribes by email and later flips the
--    switch back on in the app would stay suppressed forever.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."clear_newsletter_unsubscribe"()
RETURNS TRIGGER
LANGUAGE "plpgsql"
SECURITY DEFINER
SET "search_path" = "public"
AS $$
BEGIN
  DELETE FROM public.newsletter_unsubscribes n
  USING auth.users u
  WHERE u.id = NEW.id
    AND n.email = lower(u.email);
  RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."clear_newsletter_unsubscribe"() OWNER TO "postgres";

DROP TRIGGER IF EXISTS "on_newsletter_resubscribe" ON "public"."profiles";
CREATE TRIGGER "on_newsletter_resubscribe"
  AFTER UPDATE OF "newsletter" ON "public"."profiles"
  FOR EACH ROW
  WHEN (NEW.newsletter = true AND OLD.newsletter IS DISTINCT FROM NEW.newsletter)
  EXECUTE FUNCTION "public"."clear_newsletter_unsubscribe"();

-------------------------------------------------------------------
-- 6. Send on insert — reuses the existing notify webhook trigger
-------------------------------------------------------------------
DROP TRIGGER IF EXISTS "on_newsletter_created" ON "public"."newsletters";
CREATE TRIGGER "on_newsletter_created"
  AFTER INSERT ON "public"."newsletters"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."trigger_notify_on_record_created"();
