-- Curated, admin-managed list of Hungarian help hotlines / places for the
-- "Segítség kell?" (get-help) screen. Deliberately NOT reusing "contacts":
-- that table is owned per-row by a user/buziness (author uuid) and carries
-- business-specific triggers (e.g. "must keep at least one contact"), which
-- don't apply to a curated, nobody-owns-it hotline list.
--
-- One row per organization. Each can carry any combination of a phone
-- number (tel), a website (web) and a physical location (place), plus an
-- optional buziness_id to link the entry to a buziness page in the future.

CREATE TABLE IF NOT EXISTS "public"."help_contacts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "tel" "text",
    "web" "text",
    "place" "text",
    "buziness_id" bigint REFERENCES "public"."buziness"("id") ON DELETE SET NULL
);

ALTER TABLE "public"."help_contacts" OWNER TO "postgres";

ALTER TABLE "public"."help_contacts" ENABLE ROW LEVEL SECURITY;

-- Readable by everyone, including signed-out users looking for help.
CREATE POLICY "Enable read access for all users" ON "public"."help_contacts" FOR SELECT USING (true);

-- No INSERT/UPDATE/DELETE policies: only the postgres owner / service_role
-- (which bypass RLS) can change entries, keeping this list admin-curated.

INSERT INTO "public"."help_contacts" ("title", "description", "tel", "web", "place") VALUES
('Lelki Elsősegély Telefonszolgálat', 'Ingyenesen hívható, 24 órás lelkisegély-vonal bárkinek, aki nehéz élethelyzetben van vagy krízist él át.', '116123', 'sos116-123.hu', NULL),
('Kék Vonal Gyermekkrízis Alapítvány', 'Ingyenes, anonim, 24 órás segélyvonal gyerekeknek és fiataloknak (24 éves korig).', '116111', 'kek-vonal.hu', NULL),
('Országos Kríziskezelő és Információs Telefonszolgálat (OKIT)', 'Ingyenes, 24 órás segítség bántalmazás, gyermekbántalmazás és emberkereskedelem áldozatainak.', '0680205520', 'okit.hu', NULL),
('NANE Egyesület Segélyvonala', 'Segítség nőbántalmazás és családon belüli erőszak áldozatainak. H, K, Cs, P: 18-22, Sze: 12-14 óráig.', '0680505101', 'nane.hu', NULL),
('Áldozatsegítő Vonal', 'Ingyenes, 24 órás segítség bűncselekmények áldozatainak, az ország egész területéről hívható.', '0680225225', 'vansegitseg.im.gov.hu', NULL),
('Háttér Társaság (LMBTQI Segélyvonal)', 'Segítségnyújtás LMBTQI embereknek és hozzátartozóiknak, naponta 18-23 óráig.', '1737', 'hatter.hu', NULL),
('Krízis Ambulancia – Péterfy Kórház', 'Lélektani krízisben lévők, öngyilkossági gondolatokkal küzdők személyes, ambuláns ellátása.', NULL, 'peterfykh.hu', '1076 Budapest, Péterfy Sándor utca 8-20.');
