-- Create reports table for profile reporting
CREATE TABLE IF NOT EXISTS "public"."reports" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "author" uuid NOT NULL,
    "reported_profile_id" uuid NOT NULL,
    "reason" text NOT NULL,
    "description" text NOT NULL
);
-- Add foreign key constraints
ALTER TABLE "public"."reports"
ADD CONSTRAINT "reports_author_fkey" FOREIGN KEY ("author") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
ALTER TABLE "public"."reports"
ADD CONSTRAINT "reports_reported_profile_id_fkey" FOREIGN KEY ("reported_profile_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
-- Set table owner
ALTER TABLE "public"."reports" OWNER TO "postgres";
-- Enable Row Level Security
ALTER TABLE "public"."reports" ENABLE ROW LEVEL SECURITY;
-- Grant permissions
GRANT ALL ON TABLE "public"."reports" TO "anon";
GRANT ALL ON TABLE "public"."reports" TO "authenticated";
GRANT ALL ON TABLE "public"."reports" TO "service_role";
-- RLS Policies
-- Anyone authenticated can insert a report
CREATE POLICY "Enable insert for authenticated users" ON "public"."reports" FOR
INSERT TO "authenticated" WITH CHECK (
        (
            SELECT auth.uid()
        ) = author
    );
-- Only service_role can read reports (for admin purposes)
CREATE POLICY "Enable read for service_role only" ON "public"."reports" FOR
SELECT TO "service_role" USING (true);