-- A globális címkeszótár, ami két dolgot szolgál ki egyszerre.
--
-- 1. Autocomplete. A biznisz címkéit ma a felhasználó szabadon gépeli be
--    (components/TagInput.tsx), így ugyanaz a fogalom tucatnyi elgépelt alakban él.
--    Egy szótár, használati számlálóval, javaslatot tud tenni a bevett alakra.
-- 2. Érdeklődési körök. A felhasználó ugyanezekből a címkékből ad meg magának néhányat
--    (public.user_settings.interests, lásd a következő migrációt), és ezek rangsorolják
--    a Közösség oldal kezdeti biznisz listáját.
--
-- A számláló VALÓDI referenciaszámláló: nem "hányszor gépelték be valaha", hanem "hány
-- élő használata van most". Ezt nem lehet "mentéskor +1" logikával karbantartani —
-- a szerkesztés, a törlés és a nyers SQL írás mind elrontaná. Ezért a számláló két
-- kapcsolótáblából származik, triggerrel, és a kapcsolótáblák ON DELETE CASCADE-del
-- lógnak a forrásaikon. Amint a számláló nullára esik, a címke sora törlődik, így az
-- autocomplete csak élő címkéket kínál.
--
-- A címkéknek saját embeddingjük is van. Szándékosan NEM a public.buziness.embedding-et
-- használjuk a szemantikus illesztéshez: azt a supabase/functions/create-buziness a
-- biznisz nevéből, az ÖSSZES címkéjéből és a leírásából állítja elő egyetlen vektorba,
-- tehát egy soktémájú biznisz vektora egyik címkéjéhez sincs közel. Azon a vektoron a
-- címkék vagyolása ÉS-sé torzulna. A címke ↔ címke hasonlóság mindkét oldalon tiszta.
-- A vektorokat a supabase/functions/embed-tags tölti fel, kötegelten.

-------------------------------------------------------------------
-- Normalizálás. Ez a kulcs, amin az azonosság eldől.
--
-- Kisbetűsítünk és összevonjuk a belső whitespace-t, de ÉKEZETET NEM TÜNTETÜNK EL:
-- magyarul a "kőműves"/"komuves" összevonása többet ártana, mint használ. A megjelenített
-- alak (tags.name) az elsőként beküldött írásmód marad.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.normalize_tag(p_tag text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT btrim(regexp_replace(lower(COALESCE(p_tag, '')), '\s+', ' ', 'g'));
$$;

-------------------------------------------------------------------
-- A szótár.
-------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tags (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  normalized  text NOT NULL UNIQUE,
  usage_count integer NOT NULL DEFAULT 0,

  -- NULL = még nincs beágyazva. Ilyenkor a címke csak a szó szerinti ágon illeszt,
  -- ami elfogadható átmeneti állapot, amíg az embed-tags függvény utol nem éri.
  embedding   extensions.vector(512),
  embedded_at timestamptz,

  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Prefix-keresés az autocomplete-hez. A normalized oszlopon megy, hogy a "Kert" is
-- megtalálja a "kertészet"-et.
CREATE INDEX IF NOT EXISTS tags_normalized_prefix_idx
  ON public.tags (normalized text_pattern_ops);
CREATE INDEX IF NOT EXISTS tags_usage_count_idx
  ON public.tags (usage_count DESC, normalized);
CREATE INDEX IF NOT EXISTS tags_embedding_idx
  ON public.tags USING hnsw (embedding extensions.vector_ip_ops);

-------------------------------------------------------------------
-- Kapcsolótáblák: egy sor = egy élő használat. Külön tábla a két forrásnak, hogy az
-- ON DELETE CASCADE valódi legyen (egy polimorf source_id-vel nem lehetne FK-t tenni
-- sem a buziness-re, sem az auth.users-re).
-------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.buziness_tags (
  tag_id      bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  buziness_id bigint NOT NULL REFERENCES public.buziness(id) ON DELETE CASCADE,
  PRIMARY KEY (buziness_id, tag_id)
);
CREATE INDEX IF NOT EXISTS buziness_tags_tag_id_idx ON public.buziness_tags (tag_id);

CREATE TABLE IF NOT EXISTS public.interest_tags (
  tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  author uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  PRIMARY KEY (author, tag_id)
);
CREATE INDEX IF NOT EXISTS interest_tags_tag_id_idx ON public.interest_tags (tag_id);

-------------------------------------------------------------------
-- A számláló karbantartása, és a nullára esett címke törlése.
--
-- A törlés önmagát nem hajtja végtelen ciklusba: mire ide jutunk, a címkének már nincs
-- egyetlen kapcsolósora sem (épp ezért nulla a számláló), tehát a CASCADE nem talál
-- semmit, amin újra tüzelhetne. Ha egy párhuzamos tranzakció mégis törölte volna már a
-- címkét, az UPDATE nem talál sort, a RETURNING NULL-t ad, és nem csinálunk semmit.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.bump_tag_usage()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  remaining integer;
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.tags SET usage_count = usage_count + 1 WHERE id = NEW.tag_id;
    RETURN NEW;
  END IF;

  UPDATE public.tags SET usage_count = usage_count - 1
  WHERE id = OLD.tag_id
  RETURNING usage_count INTO remaining;

  IF remaining IS NOT NULL AND remaining <= 0 THEN
    DELETE FROM public.tags WHERE id = OLD.tag_id;
  END IF;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS buziness_tags_bump_usage ON public.buziness_tags;
CREATE TRIGGER buziness_tags_bump_usage
  AFTER INSERT OR DELETE ON public.buziness_tags
  FOR EACH ROW EXECUTE FUNCTION public.bump_tag_usage();

DROP TRIGGER IF EXISTS interest_tags_bump_usage ON public.interest_tags;
CREATE TRIGGER interest_tags_bump_usage
  AFTER INSERT OR DELETE ON public.interest_tags
  FOR EACH ROW EXECUTE FUNCTION public.bump_tag_usage();

-------------------------------------------------------------------
-- Szinkronizálók: egy címkelistából hozzák rendbe a kapcsolótáblát. Idempotensek, tehát
-- ugyanazzal a listával újra meghívva nem mozdítanak a számlálón.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sync_buziness_tags(p_buziness_id bigint, p_tags text[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  norm text[];
BEGIN
  SELECT COALESCE(array_agg(DISTINCT public.normalize_tag(raw)), ARRAY[]::text[])
    INTO norm
  FROM unnest(COALESCE(p_tags, ARRAY[]::text[])) AS raw
  WHERE public.normalize_tag(raw) <> '';

  INSERT INTO public.tags (name, normalized)
  SELECT DISTINCT ON (public.normalize_tag(raw)) btrim(raw), public.normalize_tag(raw)
  FROM unnest(COALESCE(p_tags, ARRAY[]::text[])) AS raw
  WHERE public.normalize_tag(raw) <> ''
  ON CONFLICT (normalized) DO NOTHING;

  DELETE FROM public.buziness_tags bt
  USING public.tags tg
  WHERE bt.buziness_id = p_buziness_id
    AND tg.id = bt.tag_id
    AND NOT (tg.normalized = ANY (norm));

  INSERT INTO public.buziness_tags (buziness_id, tag_id)
  SELECT p_buziness_id, tg.id
  FROM public.tags tg
  WHERE tg.normalized = ANY (norm)
  ON CONFLICT DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_interest_tags(p_author uuid, p_tags text[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  norm text[];
BEGIN
  SELECT COALESCE(array_agg(DISTINCT public.normalize_tag(raw)), ARRAY[]::text[])
    INTO norm
  FROM unnest(COALESCE(p_tags, ARRAY[]::text[])) AS raw
  WHERE public.normalize_tag(raw) <> '';

  INSERT INTO public.tags (name, normalized)
  SELECT DISTINCT ON (public.normalize_tag(raw)) btrim(raw), public.normalize_tag(raw)
  FROM unnest(COALESCE(p_tags, ARRAY[]::text[])) AS raw
  WHERE public.normalize_tag(raw) <> ''
  ON CONFLICT (normalized) DO NOTHING;

  DELETE FROM public.interest_tags it
  USING public.tags tg
  WHERE it.author = p_author
    AND tg.id = it.tag_id
    AND NOT (tg.normalized = ANY (norm));

  INSERT INTO public.interest_tags (author, tag_id)
  SELECT p_author, tg.id
  FROM public.tags tg
  WHERE tg.normalized = ANY (norm)
  ON CONFLICT DO NOTHING;
END;
$$;

-------------------------------------------------------------------
-- A biznisz oldali könyvelés triggerből megy, nem az edge functionből, hogy SEMMILYEN
-- írási út ne kerülhesse meg: a create-buziness, az admin felület és a nyers SQL is
-- ugyanide fut be.
--
-- A címkék a title-ben élnek " $ " elválasztóval, az első szegmens a biznisz neve.
-- A create-buziness normalizálja a szeparátorokat (index.ts:56-67), de egy nyers írás
-- nem, ezért a szinkronizáló amúgy is kiszórja az üres szegmenseket.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.sync_buziness_tags_from_title()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM public.sync_buziness_tags(
    NEW.id,
    (string_to_array(COALESCE(NEW.title, ''), ' $ '))[2:]
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS buziness_sync_tags ON public.buziness;
CREATE TRIGGER buziness_sync_tags
  AFTER INSERT OR UPDATE OF title ON public.buziness
  FOR EACH ROW EXECUTE FUNCTION public.sync_buziness_tags_from_title();

-------------------------------------------------------------------
-- Backfill: a meglévő bizniszek címkéi ugyanazon a kódúton mennek be, amin ezentúl
-- minden új is. Így a szótár az első pillanattól használható, és nincs külön backfill
-- logika, ami elsodródhatna a valóditól.
-------------------------------------------------------------------
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT id, title FROM public.buziness LOOP
    PERFORM public.sync_buziness_tags(r.id, (string_to_array(COALESCE(r.title, ''), ' $ '))[2:]);
  END LOOP;
END;
$$;

-------------------------------------------------------------------
-- RLS.
--
-- A tags publikusan olvasható: ez maga az autocomplete, és a tartalma amúgy is közadat
-- (minden sora egy már kiírt biznisz címkéje). Írni csak a fenti SECURITY DEFINER
-- függvények tudnak, ezért INSERT/UPDATE/DELETE policy nincs.
--
-- A kapcsolótáblák policy nélkül maradnak: kizárólag trigger írja őket, és az
-- interest_tags amúgy is azt árulná el, ki mi iránt érdeklődik.
-------------------------------------------------------------------
ALTER TABLE public.tags          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buziness_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interest_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tags are public" ON public.tags;
CREATE POLICY "tags are public" ON public.tags FOR SELECT USING (true);

GRANT SELECT ON public.tags TO anon, authenticated;

-- A szinkronizálókat csak a trigger és a service role hívja, senki más.
REVOKE EXECUTE ON FUNCTION public.sync_buziness_tags(bigint, text[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_interest_tags(uuid, text[])  FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.sync_buziness_tags(bigint, text[]) TO service_role;
GRANT  EXECUTE ON FUNCTION public.sync_interest_tags(uuid, text[])   TO service_role;

-------------------------------------------------------------------
-- Autocomplete RPC. Mintája a meglévő get_popular_search_queries
-- (20260605000000_add_popular_queries_function.sql), amit a keresőmező használ.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.search_tags(p_prefix text, p_limit integer DEFAULT 8)
RETURNS TABLE(name text, usage_count integer)
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT t.name, t.usage_count
  FROM public.tags t
  WHERE public.normalize_tag(p_prefix) <> ''
    AND t.normalized LIKE public.normalize_tag(p_prefix) || '%'
  ORDER BY t.usage_count DESC, t.normalized
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 8), 1), 20);
$$;

REVOKE EXECUTE ON FUNCTION public.search_tags(text, integer) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.search_tags(text, integer) TO anon, authenticated;

-------------------------------------------------------------------
-- Melyik címkéket szabad beágyazni.
--
-- A supabase/functions/fill-embeddings precedensét követjük: egy karbantartó job nem
-- lehet a hátsó ajtó, amin át mégis kimegy az OpenAI-hoz annak a szövege, aki az
-- "AI-s megtalálhatóság"-ot kikapcsolta. Egy címkét ezért csak akkor ágyazunk be, ha van
-- legalább egy olyan használója — biznisz szerzője vagy érdeklődési körként megadója —,
-- aki NEM kapcsolta ki a flaget.
--
-- A tisztán opt-outolt felhasználóktól származó címkék embedding nélkül maradnak; azok
-- továbbra is illeszthetők a szó szerinti ágon, csak szemantikusan nem.
--
-- A usage_count > 0 feltétel csak óvatosság: nulla számlálójú sor a trigger miatt nem
-- szokott létezni.
-------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.tags_pending_embedding(p_limit integer DEFAULT 200)
RETURNS TABLE(id bigint, name text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT t.id, t.name
  FROM public.tags t
  WHERE t.embedding IS NULL
    AND t.usage_count > 0
    AND (
      EXISTS (
        SELECT 1
        FROM public.buziness_tags bt
        JOIN public.buziness b ON b.id = bt.buziness_id
        LEFT JOIN public.user_settings s ON s.author = b.author
        WHERE bt.tag_id = t.id AND COALESCE(s.ai_enhance, false) = true
      )
      OR EXISTS (
        SELECT 1
        FROM public.interest_tags it
        LEFT JOIN public.user_settings s ON s.author = it.author
        WHERE it.tag_id = t.id AND COALESCE(s.ai_enhance, false) = true
      )
    )
  ORDER BY t.usage_count DESC, t.id
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 200), 1), 1000);
$$;

REVOKE EXECUTE ON FUNCTION public.tags_pending_embedding(integer) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.tags_pending_embedding(integer) TO service_role;
